
module.exports = {
    ARS: "ARS",
    AUD: "AUD",
    BRL: "BRL",
    CAD: "CAD",
    CHF: "CHF",
    CNY: "CNY",
    CZK: "CZK",
    DKK: "DKK",
    EUR: "EUR",
    GBP: "GBP",
    HKD: "HKD",
    INR: "INR",
    JPY: "JPY",
    KRW: "KRW",
    NOK: "NOK",
    PLN: "PLN",
    RUB: "RUB",
    SAR: "SAR",
    SEK: "SEK",
    SGD: "SGD",
    USD: "USD",
    ZAR: "ZAR"
};
